### ISSUE TITLE
the belt z axis mod

### ISSUE THREAD

**Issue by dukeGreen** [christophmuellerorg/voron_0_kirigami_bed#1]
Do you play to support the belt z axis mod?

**Comment by christophmuellerorg** [comment]
I won't support it myself, but there is one available here: https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/MathematicalPotato/v0.1_belted_z_drive/STL/Kirigami_Bed_Mount 

Obviously I have not tested it.
