### ISSUE TITLE
Chain mount problem - chain radius too small

### ISSUE THREAD

**Issue by hmouridsen** [christophmuellerorg/voron_0_kirigami_bed#12]
Hi

I think the [VORON_v0.2_stealth_chain_mount.stl] should be a little bigger. I don't know if chains are different, but I've bought the one listed in the 0.2 bom. I feel the bending radius is too small for the chain, witch means my printer struggles with the z-axis due to chain resistance
![IMG_2312](https://user-images.githubusercontent.com/47065849/224498952-b4ebd2be-a67a-4618-a518-aef679983b36.jpeg)

**Comment by christophmuellerorg** [comment]
Hi, can you measure the distance between the profile and the inside of your chain for the worst possible configuration, i.e. the top chain segment being parallel to the ground? 

Technically this mount is already widened relative to the original design and based on the chains I have here it should just fit. I might add a dragchain spacer to add a few additional mm if required.

Best,
Christoph

**Comment by hmouridsen** [comment]
Hi Christoph

First of all thanks for sharing your work.

I'm not sure if I understand you clearly, but I for my chain to move freely, without resistance, I need 2mm more. Witch means the chain mount should be 12mm instead of 10mm. A spacer could be an easy solution as well.

My chain starts to move freely at 27mm bend radius (with the top link parallel to the ground), and at the moment I measure about 24mm

At first I mounted the 0.1 chain mount witch is 9mm wide, and it made my z motor buzz.

**Comment by hmouridsen** [comment]
Hi

I did some spacer testing, and 15mm seems to be the correct size for my chain, but I guess it can vary a lot from chain to chain


![image](https://user-images.githubusercontent.com/47065849/224567574-45d94fab-6e2f-4ad8-881b-f9485d3abbe6.jpeg)

**Comment by christophmuellerorg** [comment]
I just added a 5mm spacer, please give it a try and let me know whether it works.

**Comment by hmouridsen** [comment]
> I just added a 5mm spacer, please give it a try and let me know whether it works.

Thanks a million - it's perfect - chain is absolutely moving freely now 

![image](https://user-images.githubusercontent.com/47065849/225424144-8163de63-46ba-44c7-a9d0-279365efc363.jpeg)
