### ISSUE TITLE
v0.2 belt chain mount question

### ISSUE THREAD

**Issue by chrisheninger** [christophmuellerorg/voron_0_kirigami_bed#13]
Hi Christoph (or anyone reading these issues that might know the answer!)–

I'm building a v0.2 kit from Formbot3d.

It came with a kirigami bed– and I'm trying to figure out where the `VORON_v0.2_belt_chain_mount` belongs. I've noticed a lot of the pictures/diagrams in the repo show different variations/versions and I haven't seemed to be able to find anything online showing different angles of the v0.2.

Here's a photo:

<img width="600" alt="image" src="https://github.com/christophmuellerorg/voron_0_kirigami_bed/assets/5051745/52b01dde-9578-460e-a0f6-e1d8fb9ad837">

Thank you!

Edit: After thinking about it a little longer... I'm realizing that I don't need the "belt chain mount" because I'm using the "stealth chain mount" and spacer?

**Comment by Schlonky** [comment]
Yes, the belt chain mount is if you're using the Belt Chain usermod. So it's not needed for you
