### ISSUE TITLE
Formbot Bed Thermal Fuse Collides with Frame

### ISSUE THREAD

**Issue by SrgntBallistic** [christophmuellerorg/voron_0_kirigami_bed#17]
My Formbot V0.2 kit includes a thermal fuse and has a pre-drilled/tapped hole for mounting it.

I mounted it in this location and with the bed to the rear-most position allowed by the bed screw slots the fuse collides with the bed frame on the slanted transition bit before the fuse cutout.

![image](https://github.com/christophmuellerorg/voron_0_kirigami_bed/assets/25190883/5e0e3b39-5720-4810-bc93-dbda7aecd7b1)

With the collision I'm not able to lower the bed enough to ensure the nozzle doesn't collide with the bed in that corner.

I can move the bed forward in the slots but I'll end up losing about 3mm of volume in the Y which I'm trying to avoid.

I looked at the V0 drawing for the bed and they don't seem to state how far away from the edge the fuse should be mounted. So I don't think the Formbot bed is out of spec in that regard.
![image](https://github.com/christophmuellerorg/voron_0_kirigami_bed/assets/25190883/a4737b8e-bb4c-4e29-b7c5-47c069b81a28)

I'm debating a few solutions

1. Re drilling/tapping the mounting hole for the fuse
2. Removing some material from the fuse
3. Removing some material from the bed
4. Mounting the fuse to the silicone pad with RTV

I'm not suggesting any revisions to account for this. Maybe just a callout noting that there could be issues or a suggestion for handling this.

**Comment by christophmuellerorg** [comment]
Please open a complaint with Formbot so that they can fix it in their next batch, should be solvable by placing the fuse mounting hole further inside towards the center of the bed.

I use a Fermio bed here which seems to just work. The cutout was introduced before the slot which allows to shift the bed backwards and forwards for fine tuning of the location, debending on the extruder used. I don't think it would be wise to extend the fuse cutout even further back, considering the stability of the bed.

**Comment by SrgntBallistic** [comment]
> Please open a complaint with Formbot so that they can fix it in their next batch, should be solvable by placing the fuse mounting hole further inside towards the center of the bed.
> 
> I use a Fermio bed here which seems to just work. The cutout was introduced before the slot which allows to shift the bed backwards and forwards for fine tuning of the location, debending on the extruder used. I don't think it would be wise to extend the fuse cutout even further back, considering the stability of the bed.

Thanks Christoph. Feel free to close this. I just wanted to bring it to your attention. I have a list of issues/concerns/improvements I'm giving to Formbot. They provided this kit for review. 

In another post about the Formbot frame thickness I noted I can send you one of their frames. Please let me know if you'd like one. I ordered a number of items from their site including an extra frame. I'm happy to send it along.

Thanks for the great mod!
