### ISSUE TITLE
chain too close to back panel

### ISSUE THREAD

**Issue by Matszwe02** [christophmuellerorg/voron_0_kirigami_bed#18]
The cable chain is too close to the back panel and it keeps scratching the acrylic, in my case. I think there's a tiny bit of play to this chain, but it's hardly achieveable to have it not scratch.
![20230627_221342](https://github.com/christophmuellerorg/voron_0_kirigami_bed/assets/49353902/62d0292b-c014-49f9-aeb8-cf57c5508cee)

**Comment by christophmuellerorg** [comment]
Seems like you mounted the end cap of the chain the wrong way around, compare to 
![grafik](https://github.com/christophmuellerorg/voron_0_kirigami_bed/assets/2552922/005df75e-58a5-4c32-ba60-6a3612066d38)

Finally, there are dozens of chains out there and I cannot test all - for example, I have never seen this one in particular. The location of the chain mount is identical to the stock design, so if your chain does not work well you would have the same trouble. The V0 is a tight design and there is very little clearance in this location, scratches can happen and are purely cosmetic.

**Comment by Matszwe02** [comment]
> Seems like you mounted the end cap of the chain the wrong way around, compare to 
> ![grafik](https://github.com/christophmuellerorg/voron_0_kirigami_bed/assets/2552922/005df75e-58a5-4c32-ba60-6a3612066d38)
> 
> Finally, there are dozens of chains out there and I cannot test all - for example, I have never seen this one in particular. The location of the chain mount is identical to the stock design, so if your chain does not work well you would have the same trouble. The V0 is a tight design and there is very little clearance in this location, scratches can happen and are purely cosmetic. 

Hi. Thanks for the reply. I have some chain that came with a formbot kit, which bends "the wrong way", so I had to rotate it. Now I figured out that my electronics may have a tight fit and cause the acrylic to bend towards the chain
