### ISSUE TITLE
Thicker body for heat set inserts in V0.2 nut block?

### ISSUE THREAD

**Issue by Kagee** [christophmuellerorg/voron_0_kirigami_bed#20]
Is there a reason the bottom of the nut block can not be slightly thicker, thus think enough to have a bottom for the heat set inserts, and making it harder to fail and press them through?

![image](https://github.com/christophmuellerorg/voron_0_kirigami_bed/assets/686579/942c05a6-188d-48f2-a5aa-344fddac3cd0)

**Comment by christophmuellerorg** [comment]
The shallow depth is there to keep backwards compatibility to V0.0.

**Comment by Kagee** [comment]
Hmm, yes, but would not V0.0 users use the other STL with a screw hole for the top-mounted Z-endstop anyway? So in theory the v0.2 block could be thicker?
