### ISSUE TITLE
JST connectors missing from the BOM

### ISSUE THREAD

**Issue by KreativeLabs** [christophmuellerorg/voron_0_kirigami_bed#9]
I purchased this kit but 2pcs JST connectors are missing feom the list to be able to split the thermistor wires. I didn’t have those at hand so I have to pause the conversion. Do I misunderstand something about the build?

**Comment by christophmuellerorg** [comment]
The PCB is not part of the Kirigami bed project but an addition by LDO I have no control over.

**Comment by KreativeLabs** [comment]
Oh I see :)
